### ISSUE TITLE
Warning: include(.../format-api/build/index.asset.php): failed to open stream: No such file or directory in ...format-api/index.php on line 20

### ISSUE THREAD

**Issue by mipon** [WordPress/gutenberg-examples#183] opened 2021-12-25 17:57 UTC
The current `trunk` branch produces the following warning.

```
Warning: include(wp-content/plugins/gutenberg-examples/format-api/build/index.asset.php): failed to open stream: No such file or directory in .../wp-content/plugins/gutenberg-examples/format-api/index.php on line 20
```

It appears the build files are missing.

**Comment by ryanwelcher** [comment] 2022-03-09 18:47
I believe this has been addressed but can you confirm that this is still an issue for you?

**Comment by ryanwelcher** [comment] 2022-03-24 16:12
There has been no movement on this and I cannot reproduce locally. Closing for now but feel free to re-open if the issue persists.

**Closed as completed by ryanwelcher** 2022-03-24 16:12 UTC
Labels: bug, [Status] Needs More Info

**Comment by tiennguyenvan** [comment] 2022-12-23 08:32
![image](https://user-images.githubusercontent.com/12868514/209301318-38b113f0-1458-4f51-ba7d-fb810ed1c885.png)
I have the same issue.

"npm run build:all" does not also generate anything. It says: "wp-scripts" is not regconized.
![image](https://user-images.githubusercontent.com/12868514/209301868-775a5ead-4b77-416e-8d1c-e2614be59ba3.png)

I a new developer on this topic, correct me if I am stupid. Thank you very much.

**Comment by KevinBatdorf** [comment] 2022-12-23 13:23
@tiennguyenvan did you run `npm install` first?

**Comment by tiennguyenvan** [comment] 2022-12-23 13:55
@KevinBatdorf I did and here is the screenshot after running:
![image](https://user-images.githubusercontent.com/12868514/209347222-86593e0b-2bb7-4638-afde-e2f00d524f28.png)

**Comment by KevinBatdorf** [comment] 2022-12-23 14:11
The dependencies need to be updated. The lock file looks to be out of sync as well.

You have two options for now (only do one):

Option 1:
Change line 23 in [package.json](https://github.com/WordPress/gutenberg-examples/blob/trunk/package.json#L23) to `"prettier": "npm:wp-prettier@^2.6.2"` then run `npm i` again

Option 2:
Don't change anything, but run `npm i --force` (In general, using `--force` is not something you should want to rely on, so think of this as a temporary hack)

**Comment by tiennguyenvan** [comment] 2022-12-23 14:21
Thank you very much. Both options worked well for the npm install. But here are the errors for "npm run build:all"
![image](https://user-images.githubusercontent.com/12868514/209350292-b4f1d1bc-5b5d-4df1-bd46-a5b9da0fb24a.png)

I also manually created a plugin following the structure of this plugin but my block does not show in the block list of the editor.
![image](https://user-images.githubusercontent.com/12868514/209350884-009073e4-4f3d-4830-8f50-2a7624c0bcf5.png)

This is the reason why I love to see the example plugin run in real to start learning from it.
Thanks a lot.

**Comment by KevinBatdorf** [comment] 2022-12-23 14:29
Try using node 16.18.0 to resolve the error. I'm not sure as I've never seen that error before, but my guess is you're on a newer version of Node.

> I also manually created a plugin following the structure of this plugin but my block does not show in the block list of the editor.

Nothing will show until you get the bundler to build the package successfully without errors.

**Comment by tiennguyenvan** [comment] 2022-12-23 14:57
@KevinBatdorf Wow. You are correct. After updating the Node to the latest version, I could build the package properly. Thank you very much. You saved my day. Merry Christmas.

**Comment by tiennguyenvan** [comment] 2022-12-23 15:34
@KevinBatdorf This question could be stupid: if I am trying to create a similar plugin that provides extra blocks so I just clone this package, replace the name, modify the code and build then it will work the same, is that right?

I am really new to Node.

Thank you very much, Kevin.

**Comment by KevinBatdorf** [comment] 2022-12-23 15:40
The question is fine. You're better off opening a new issue though to discuss that. I'm also not the best person to answer it.

I _think_ you would want to use the [create-block](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/) package and then go from there. I'm not sure how up to date the documentation is though, so you may need to just keep at it and do a lot of Google searching.

@ryanwelcher has a bunch of YouTube videos as well you can check out: https://www.youtube.com/c/RyanWelcherCodes

**Comment by tiennguyenvan** [comment] 2022-12-23 15:46
@KevinBatdorf Thank you, Kevin. I subscribed to @ryanwelcher's channel. I will create other tickets if needed. Nice to meet you here, Kevin.
